version: '3'

services:
  mysql-core:
    container_name: "mysql-core"
    image: "mysql:latest"
    environment:
      TZ: Asia/Tehran
      MYSQL_ROOT_PASSWORD: 33443344
      MYSQL_DATABASE: cyber-center
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql


  redis-core:
    container_name: "redis-core"
    image: "redis:latest"
    command: redis-server
    ports:
      - 6397:6379